name: Windows Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true

jobs:
  build:
    runs-on: windows-latest 
    permissions:
      contents: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall toml-cli
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v7
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true

      - name: Create Signed Git Tag
        run: |
          git tag -s v${{ github.event.inputs.tag }} -m v${{ github.event.inputs.tag }}
          git push origin v${{ github.event.inputs.tag }}
      - name: Prepare release
        run: |
          toml set Cargo.toml package.version ${{ github.event.inputs.tag }} > temp.toml
          Move-Item -Path temp.toml -Destination Cargo.toml -Force
      - name: Build
        run: cargo build --release
      - name: Create archives
        run: 7z a -tzip dist/picarus.zip ./target/release/picarus.exe
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ github.event.inputs.tag }}
          files: dist/picarus.zip
          generate_release_notes: true